language: scala
scala:
- 2.11.8
jdk:
- oraclejdk8
script:
- sbt test

before_install:
- if [ "$TRAVIS_BRANCH" = "master" -a "$TRAVIS_PULL_REQUEST" = "false" ]; then
     openssl aes-256-cbc -K $encrypted_e3665000fc5c_key -iv $encrypted_e3665000fc5c_iv -in secring.gpg.enc -out secring.gpg -d;
  fi

after_success:
- if [ "$TRAVIS_BRANCH" = "master" -a "$TRAVIS_PULL_REQUEST" = "false" ]; then
     sbt compile publishSigned;
  fi
- if [ "$TRAVIS_PULL_REQUEST" = "true" ]; then
     echo "Not in master branch, skipping deploy and release";
  fi
